import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { initializeFirebase } from '../public/push-notification';
import { askForPermissionToReceiveNotifications } from '../public/push-notification';

export default function Home() {
  const coffees = [
    { name: "Perspiciatis", image: "/coffee.JPG" },
    { name: "Voluptatem", image: "/coffee.JPG" },
    { name: "Explicabo", image: "/coffee.JPG" },
    { name: "Rchitecto", image: "/coffee.JPG" },
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>PWA Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className={styles.main}>
      <div className={styles.header}>
        <img src="/logo.png" width="274" height="70" className={styles.logonagarro} alt="logo"/>
        <button onClick={askForPermissionToReceiveNotifications} >
          Click to receive notifications
        </button>

        </div>
        <div className={styles.grid}>

          {
            coffees.map((item) => {
              return (
              <div className={styles.card} key={item?.name}>
                <img src={item?.image} width="250" height="187"  alt='coffee'/>
                <h1>{item?.name}</h1>
                <a href="#">Taste</a>
            </div>)
          })
        }</div></main>


    
    </div >
  )
}

initializeFirebase();

